"use server";

const githubToken = process.env.GITHUB_TOKEN;

export type PrResult = {
  success: boolean;
  error?: string;
  prUrl?: string;
};

export async function createFixPr({
  owner,
  repo,
  baseBranch,
  fileName,
  fixedFileContent,
  commitMessage,
  testFileName,
  testFileContent,
}: {
  owner: string;
  repo: string;
  baseBranch: string;
  fileName: string;
  fixedFileContent: string;
  commitMessage: string;
  testFileName?: string;
  testFileContent?: string;
}): Promise<PrResult> {
  if (!githubToken) {
    return { success: false, error: "GITHUB_TOKEN is missing. Cannot create PR." };
  }

  const headers = {
    Authorization: `Bearer ${githubToken}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
  };

  try {
    // 1. Get Base Commit & Tree
    const refRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${baseBranch}`, { headers });
    if (!refRes.ok) throw new Error("Could not find base branch reference");
    const refData = await refRes.json();
    const baseCommitSha = refData.object.sha;

    const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits/${baseCommitSha}`, { headers });
    if (!commitRes.ok) throw new Error("Could not get base commit");
    const commitData = await commitRes.json();
    const baseTreeSha = commitData.tree.sha;

    // 2. Post Blobs
    const postBlob = async (content: string) => {
      const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/blobs`, {
        method: "POST", headers,
        body: JSON.stringify({ content, encoding: "utf-8" })
      });
      if (!res.ok) throw new Error("Failed to upload blob");
      const data = await res.json();
      return data.sha;
    };

    const treeData: any[] = [
      { path: fileName, mode: "100644", type: "blob", sha: await postBlob(fixedFileContent) }
    ];

    if (testFileName && testFileContent) {
      treeData.push({ path: testFileName, mode: "100644", type: "blob", sha: await postBlob(testFileContent) });
    }

    // 3. Create New Tree
    const newTreeRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/trees`, {
      method: "POST", headers,
      body: JSON.stringify({ base_tree: baseTreeSha, tree: treeData })
    });
    if (!newTreeRes.ok) throw new Error("Could not create new tree");
    const newTreeData = await newTreeRes.json();
    const newTreeSha = newTreeData.sha;

    // 4. Create Commit
    const newCommitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits`, {
      method: "POST", headers,
      body: JSON.stringify({ message: commitMessage, tree: newTreeSha, parents: [baseCommitSha] })
    });
    if (!newCommitRes.ok) throw new Error("Could not create commit");
    const newCommitData = await newCommitRes.json();
    const newCommitSha = newCommitData.sha;

    // 5. Create new branch passing the new commit SHA
    const newBranchName = `opscord-fix-${Date.now()}`;
    const newBranchRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
      method: "POST", headers,
      body: JSON.stringify({ ref: `refs/heads/${newBranchName}`, sha: newCommitSha })
    });
    if (!newBranchRes.ok) throw new Error("Could not create new branch");

    // 6. Create PR
    const prBody = `### OpsCord Automated Remediation\n\nThis PR was automatically generated by OpsCord's AI Multi-Agent Swarm.\n\n**Modified files:**\n- \`${fileName}\`${testFileName ? `\n- \`${testFileName}\` (Automated Unit Tests)` : ""}`;
    const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: "POST", headers,
      body: JSON.stringify({ title: commitMessage, head: newBranchName, base: baseBranch, body: prBody }),
    });
    
    if (!prRes.ok) throw new Error("Could not create Pull Request");
    const prData = await prRes.json();

    return { success: true, prUrl: prData.html_url };
  } catch (error: any) {
    return { success: false, error: error.message || "Failed to create PR" };
  }
}
