'use client';
import {dependencies,serviceCatalog} from '@/lib/domain';
import { Activity, ArrowRight, ArrowUpRight, Bell, Box, Check, ChevronDown, ChevronRight, CircleAlert, Clock3, Database, FileText, GitBranch, GitCommitHorizontal as Github, LayoutDashboard, Link2, Network, Play, Plus, Radio, RefreshCw, Server, ShieldCheck, Sparkles, Thermometer, TriangleAlert, Users, Waypoints, Workflow } from 'lucide-react';
import {Sidebar, SidebarProvider, SidebarContent, SidebarHeader, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription} from '@/components/ui/dialog';

export function Panel({title,sub,icon:Icon,action,children,className=''}: {title:string;sub?:string;icon?:typeof Activity;action?:React.ReactNode;children:React.ReactNode;className?:string}) {return <section className={`panel ${className}`}><div className="panel-head"><div><h2>{Icon&&<Icon size={17}/>} {title}</h2>{sub&&<p>{sub}</p>}</div>{action}</div>{children}</section>}
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}

export function Telemetry({onExplore}:{onExplore:()=>void}){return <Panel title="IoT telemetry" sub="Signals from the physical world" icon={Radio} className="telemetry-panel"><div className="sensor-title"><span>Temperature sensor</span><Badge tone="teal">Anomaly</Badge></div><div className="sensor-id">TEMP-1847 <span>·</span> Rack 3, Edge lab</div><div className="temperature"><span className="temperature-icon"><Thermometer size={35}/></span><div><strong>98.6<span>°C</span></strong><small>23.6°C above threshold</small></div></div><div className="chart-label"><span>Temperature</span><span>Threshold 75°C</span></div><svg className="temp-chart" viewBox="0 0 260 122" role="img" aria-label="Temperature rose from 64 to 98.6 degrees between 10:30 and 11:19"><defs><linearGradient id="temp-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#0eafac" stopOpacity=".17"/><stop offset="1" stopColor="#0eafac" stopOpacity="0"/></linearGradient></defs><path d="M0 102 L15 88 L30 94 L45 85 L60 90 L75 75 L90 83 L105 67 L120 73 L135 60 L150 64 L165 43 L180 49 L195 32 L210 27 L225 12 L245 9 L245 118 L0 118Z" fill="url(#temp-fill)"/><path d="M0 102 L15 88 L30 94 L45 85 L60 90 L75 75 L90 83 L105 67 L120 73 L135 60 L150 64 L165 43 L180 49 L195 32 L210 27 L225 12 L245 9" fill="none" stroke="#0daba5" strokeWidth="2.5"/><path d="M0 76 H260" stroke="#c2d9dd" strokeDasharray="4 4"/><circle cx="245" cy="9" r="4.5" fill="#0daba5" stroke="white" strokeWidth="2"/></svg><div className="chart-times"><span>10:30</span><span>11:00</span><span>11:19</span></div><div className="telemetry-flow"><div><span className="flow-icon teal"><Server size={21}/></span><div><strong>Edge processing</strong><small>edge-telemetry</small><span className="amber-text">Degraded</span></div></div><span className="flow-line">↓</span><div><span className="flow-icon blue"><Network size={21}/></span><div><strong>Forwarded to platform</strong><small>Ingested at 11:19:02</small><span className="teal-text"><Check size={12}/> Evidence linked</span></div></div></div><button className="text-btn teal-text" onClick={onExplore}>Explore telemetry <ArrowRight size={15}/></button></Panel>}

export function DependencyGraph({onSelect,demo=true}:{onSelect:(id:string)=>void;demo?:boolean}){
 const positions:Record<string,[number,number]>={'client-apps':[7,46],'api-gateway':[26,46],'auth-service':[46,10],'payment-api':[48,44],'order-service':[70,20],'database':[92,44],'worker-node':[70,62],'edge-telemetry':[46,82],'redis-cache':[92,86],'edge-device':[69,95]};
 const glyphs:Record<string,typeof Activity>={'client-apps':Users,'api-gateway':Network,'auth-service':ShieldCheck,'payment-api':CircleAlert,'order-service':Box,'database':Database,'worker-node':Server,'edge-telemetry':Radio,'redis-cache':Server,'edge-device':Thermometer};
 return <div className="dependency-graph complete-graph"><svg viewBox="0 0 800 340" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="dep-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="none" stroke="#aebcd3"/></marker></defs>{dependencies.map(e=>{const a=positions[e.from],b=positions[e.to];const dx=(b[0]-a[0])*8,dy=(b[1]-a[1])*3.4,len=Math.hypot(dx,dy);return <line key={e.from+e.to} x1={a[0]*8+dx/len*23} y1={a[1]*3.4+dy/len*23} x2={b[0]*8-dx/len*25} y2={b[1]*3.4-dy/len*25} stroke={demo&&e.to==='payment-api'?'#f6849c':'#c6d2e4'} strokeWidth="1.4" strokeDasharray={e.to==='payment-api'?'':'4 4'} markerEnd="url(#dep-arrow)"/>})}</svg>{serviceCatalog.map(s=>{const [x,y]=positions[s.id],Icon=glyphs[s.id];const tone=demo?(s.status==='failing'?'red':s.status==='degraded'?'amber':'blue'):'blue';return <button key={s.id} className={`graph-node ${tone}`} style={{left:x+'%',top:y+'%'}} onClick={()=>onSelect(s.id)}><span><Icon size={20}/></span><strong>{s.name.replace(' · Rack 3','').replace(' 03','')}</strong></button>})}</div>
}
