'use client';
import {useCallback,useEffect,useState} from 'react';
import {ArrowRight,BookOpen,Check,CheckCheck,ClipboardList,Clock3,Copy,Download,FileCheck2,Flag,Plus,RefreshCw,Save,Search,Users} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {toast} from 'sonner';
import {api,Picker} from './dashboard';
import {Panel,Badge} from './opscord';
import {type Workspace,type Incident,type EvidenceEvent,serviceCatalog} from '@/lib/domain';
import {type Coordination,type ActionItem,type ResponseData,type Postmortem,type OperationsData,type Runbook,taskStatusLabel,incidentMetrics,formatDuration} from '@/lib/response';

const options=(values:string[])=>values.map(value=>({value,label:value.replaceAll('_',' ')}));
const displayTime=(iso:string|null)=>iso?new Date(iso).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'Not scheduled';
const localTime=(iso:string|null)=>{if(!iso)return '';const date=new Date(iso);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const utcTime=(value:string)=>value?new Date(value).toISOString():null;
// Temporary drafts are device-local; all saved response records remain in D1.
function useSavedDraft<T>(key:string,value:T){
 const [initial]=useState(()=>{try{const saved=sessionStorage.getItem(key);if(saved)return {draft:JSON.parse(saved) as T,dirty:true};}catch{}return {draft:value,dirty:false};});
 const [draft,setDraft]=useState(initial.draft),[dirty,setDirty]=useState(initial.dirty);
 useEffect(()=>{try{if(dirty)sessionStorage.setItem(key,JSON.stringify(draft));else sessionStorage.removeItem(key);}catch{}},[key,draft,dirty]);
 return {draft,setDraft,dirty,setDirty};
}
type Mutate=(action:unknown)=>Promise<void>;
function download(name:string,text:string,type='text/markdown'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Loading(){return <div className="ops-loading"><RefreshCw className="spin" size={20}/> Loading response workspace…</div>;}
function Failure({message,onRetry}:{message:string;onRetry:()=>void}){return <div className="error-banner" role="alert"><span>{message}</span><button className="btn" onClick={onRetry}>Retry</button></div>;}
function Empty({title,description}:{title:string;description:string}){return <div className="ops-empty"><ClipboardList size={24}/><h3>{title}</h3><p>{description}</p></div>;}

export function ResponseWorkspace({data,view,onStatus,onNavigate}:{data:Workspace;view:string;onStatus:(status:string)=>void;onNavigate:(view:string)=>void}){
 const [response,setResponse]=useState<ResponseData|null>(null),[error,setError]=useState(''),[task,setTask]=useState<ActionItem|'new'|null>(null),[refresh,setRefresh]=useState(0);
 const id=data.incident.id;
 useEffect(()=>{let active=true;api<ResponseData>(`/api/incidents/${id}/response`).then(r=>{if(active){setResponse(r);setError('')}}).catch(e=>active&&setError(e.message));return()=>{active=false}},[id,data,refresh]);
 const mutate:Mutate=async action=>{try{const r=await api<ResponseData>(`/api/incidents/${id}/response`,'POST',action);setResponse(r);setError('');}catch(e){try{setResponse(await api<ResponseData>(`/api/incidents/${id}/response`));}catch{}throw e;}};
 if(!response)return error?<Failure message={error} onRetry={()=>setRefresh(v=>v+1)}/>:<Loading/>;
 const open=response.tasks.filter(t=>t.status!=='done'),overdue=open.filter(t=>t.dueAt&&Date.parse(t.dueAt)<Date.now());
 const report=()=>exportResponse(data,response);
 const copy=async()=>{const text=[`${data.incident.id} · ${data.incident.title}`,`Status: ${data.incident.status} | Commander: ${response.coordination.owner||'Unassigned'}`,`Impact: ${response.coordination.impact||'Not recorded'}`,`Current update: ${response.coordination.summary||'Not recorded'}`,`Next update: ${displayTime(response.coordination.nextUpdateAt)}`,`Open actions (${open.length}):`,...open.map(t=>`- ${t.title} — ${t.owner||'Unassigned'} (${taskStatusLabel(t.status)})`),`Investigation: ${location.origin}/?view=Response&incident=${encodeURIComponent(id)}`].join('\n');try{await navigator.clipboard.writeText(text);toast.success('Handoff copied. Share it with the next responder.');}catch{download(`${id}-handoff.txt`,text,'text/plain');toast.info('Handoff downloaded because clipboard access was unavailable.');}};
 return <div className="ops-surface">
  {error&&<Failure message={error} onRetry={()=>setRefresh(v=>v+1)}/>}
  <div className="response-banner"><div><div className="ops-kicker">{id} {data.incident.mode==='demo'&&'· SAMPLE SCENARIO'}</div><h2>{data.incident.title}</h2><div className="response-meta"><Badge tone={data.incident.status==='resolved'?'teal':'red'}>{data.incident.status}</Badge><span>{data.incident.service}</span><span><Users size={14}/>{response.coordination.owner||'Commander unassigned'}</span></div></div><div className="response-banner-actions"><button className="btn" onClick={copy}><Copy size={15}/> Copy handoff</button><button className="btn" onClick={report}><Download size={15}/> Export report</button><button className="btn primary" onClick={()=>onStatus(data.incident.status==='active'?'investigating':data.incident.status==='investigating'?'resolved':'active')}>{data.incident.status==='active'?'Start investigating':data.incident.status==='investigating'?'Resolve incident':'Reopen incident'}<ArrowRight size={15}/></button></div></div>
  <div className="response-stats"><div><span>Open actions</span><strong>{open.length}</strong></div><div className={overdue.length?'overdue':''}><span>Overdue</span><strong>{overdue.length}</strong></div><div><span>Completed</span><strong>{response.tasks.length-open.length}<small> / {response.tasks.length}</small></strong></div><div><span>Next update</span><strong className="date-stat">{displayTime(response.coordination.nextUpdateAt)}</strong>{response.coordination.nextUpdateAt&&Date.parse(response.coordination.nextUpdateAt)<Date.now()&&data.incident.status!=='resolved'&&<small className="red-text">Update due</small>}</div></div>
  {view==='Postmortem'?<PostmortemEditor key={id} data={data} response={response} onSave={async body=>{try{setResponse(await api<ResponseData>(`/api/incidents/${id}/response`,'PUT',body));}catch(e){try{setResponse(await api<ResponseData>(`/api/incidents/${id}/response`));}catch{}throw e;}}} onActions={()=>onNavigate('Response')}/>:<>
  {data.incident.resolutionSummary&&<div className="resolution-summary"><CheckCheck size={20}/><div><strong>Resolution recorded</strong><p>{data.incident.resolutionSummary}</p><button onClick={()=>onNavigate('Postmortem')}>Continue the postmortem <ArrowRight size={14}/></button></div></div>}
  <Tabs defaultValue="response" className="response-tabs"><TabsList><TabsTrigger value="response">Response plan</TabsTrigger><TabsTrigger value="activity">Activity & decisions <span className="tab-count">{response.activity.length}</span></TabsTrigger></TabsList>
   <TabsContent value="response"><div className="response-columns"><Panel title="Response brief" sub="A shared starting point for the next responder" icon={Users}><CoordinationForm key={id} value={response.coordination} mutate={mutate}/></Panel><Panel title="Action plan" sub="Assign a next step, then track the outcome" icon={ClipboardList} action={<button className="btn primary" onClick={()=>setTask('new')}><Plus size={15}/> Add action</button>}><div className="ops-panel-body"><div className="runbook-prompt"><BookOpen size={18}/><p>Start with a repeatable response checklist.</p><button onClick={()=>onNavigate('Runbooks')}>Browse runbooks <ArrowRight size={14}/></button></div>{response.tasks.length?response.tasks.map(t=><TaskRow key={t.id} task={t} onEdit={()=>setTask(t)} onToggle={async()=>{await mutate({action:'update_task',id:t.id,data:taskPayload(t,t.status==='done'?'open':'done')});}}/>):<Empty title="Your next step starts here" description="Add a mitigation action or apply a runbook. Each action can have an owner, deadline, and linked evidence."/>}</div></Panel></div></TabsContent>
   <TabsContent value="activity"><div className="response-columns activity-columns"><Panel title="Decision log" sub="Record what changed, why, and what remains uncertain" icon={Flag}><DecisionForm mutate={mutate}/></Panel><Panel title="Response activity" sub="Workspace activity; individual identities are not verified" icon={Clock3}><div className="ops-panel-body">{response.activityTruncated&&<p className="ops-hint">Showing the latest 200 entries.</p>}{response.activity.length?<ol className="activity-log">{response.activity.map(a=><li key={a.id}><span className={`activity-dot ${a.kind}`}/><div><div className="activity-label"><Badge>{a.kind}</Badge><time>{displayTime(a.createdAt)}</time></div><p>{a.message}</p></div></li>)}</ol>:<Empty title="No response activity yet" description="Saved briefs, actions, decisions, notes, and status changes will appear here. Older activity is not reconstructed."/>}</div></Panel></div></TabsContent>
  </Tabs></>}
  <TaskDialog task={task&&task!=='new'?(response.tasks.find(t=>t.id===task.id)??task):task} incidentId={id} evidence={data.events} onClose={()=>setTask(null)} onSave={mutate}/>
 </div>;
}

function CoordinationForm({value,mutate}:{value:Coordination;mutate:Mutate}){
 const {draft,setDraft,dirty,setDirty}=useSavedDraft(`opscord:draft:${value.incidentId}:brief`,value);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!dirty)setDraft(value)},[value,dirty]);
 const field=<K extends keyof Coordination>(key:K,v:Coordination[K])=>{setDraft({...draft,[key]:v});setDirty(true);};
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const {incidentId,updatedAt,...data}=draft;try{await mutate({action:'coordination',data});setDirty(false);toast.success('Response brief saved.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form className="ops-panel-body" onSubmit={save}><fieldset className="ops-form" disabled={busy}>
  <div className="form-grid"><label>Incident commander<Input value={draft.owner} onChange={e=>field('owner',e.target.value)} maxLength={120} placeholder="Name or team"/></label><label>Communications lead<Input value={draft.communicationsLead} onChange={e=>field('communicationsLead',e.target.value)} maxLength={120} placeholder="Name or team"/></label></div><p className="ops-hint">Names are assignments only. They do not invite people or send notifications.</p>
  <label>Customer impact<Textarea value={draft.impact} onChange={e=>field('impact',e.target.value)} maxLength={5000} rows={3} placeholder="Who is affected, and what cannot they do?"/></label>
  <label>Current situation<Textarea value={draft.summary} onChange={e=>field('summary',e.target.value)} maxLength={5000} rows={3} placeholder="What do we know? What is the next mitigation?"/></label>
  <div className="form-grid"><label>Environment<Picker label="Incident environment" value={draft.environment} onChange={v=>field('environment',v as Coordination['environment'])} options={options(['production','staging','development','unknown'])}/></label><label>Next update (your local time)<Input type="datetime-local" value={localTime(draft.nextUpdateAt)} onChange={e=>field('nextUpdateAt',utcTime(e.target.value))}/></label></div>
  <label>Response channel link<Input type="url" value={draft.channelUrl} onChange={e=>field('channelUrl',e.target.value)} maxLength={500} placeholder="https://…"/></label>
  {draft.version!==value.version&&<div className="notice">A newer brief is available. Your draft is kept on this device. Compare the current record before choosing which text to keep.<details><summary>Compare saved brief</summary><pre>{JSON.stringify(value,null,2)}</pre></details><button type="button" className="btn" onClick={()=>{setDraft(value);setDirty(false);setError('');}}>Load saved brief</button><button type="button" className="btn" onClick={()=>{setDraft({...draft,version:value.version});setError('');}}>Keep my draft over this version</button></div>}
  {error&&<p className="form-error" role="alert">{error}</p>}
  <div className="form-actions"><span className="ops-hint">{dirty?'Unsaved changes':value.updatedAt?`Saved ${displayTime(value.updatedAt)}`:'No brief saved yet'}</span><button className="btn primary" disabled={busy} type="submit"><Save size={15}/>{busy?'Saving…':'Save brief'}</button></div>
 </fieldset></form>;
}
function taskPayload(task:ActionItem,status=task.status){return {title:task.title,owner:task.owner,priority:task.priority,category:task.category,status,dueAt:task.dueAt,evidenceId:task.evidenceId,version:task.version};}
function TaskRow({task:t,onEdit,onToggle,incident,onOpen}:{task:ActionItem;onEdit:()=>void;onToggle:()=>Promise<void>;incident?:Incident;onOpen?:()=>void}){
 const [busy,setBusy]=useState(false);const late=t.status!=='done'&&t.dueAt&&Date.parse(t.dueAt)<Date.now();
 async function toggle(){setBusy(true);try{await onToggle();toast.success(t.status==='done'?'Action reopened.':'Action completed.');}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <div className={`action-row ${t.status==='done'?'is-done':''}`}><Checkbox checked={t.status==='done'} disabled={busy} onCheckedChange={()=>void toggle()} aria-label={`${t.status==='done'?'Reopen':'Complete'} ${t.title}`}/><div className="action-content"><button className="action-title" onClick={onEdit}>{t.title}</button><div className="action-details"><span><Users size={13}/>{t.owner||'Unassigned'}</span><Badge tone={t.priority==='high'?'red':'neutral'}>{t.priority}</Badge><span>{t.category==='follow_up'?'Follow-up':'Mitigation'}</span>{t.dueAt&&<span className={late?'red-text':''}><Clock3 size={13}/>{late?'Overdue · ':''}{displayTime(t.dueAt)}</span>}{t.evidenceId&&<span>Evidence linked</span>}</div>{incident&&<button className="task-incident-link" onClick={onOpen}>{incident.title}{incident.mode==='demo'?' · Sample':''}<ArrowRight size={12}/></button>}</div><button className="action-state" onClick={onEdit}>{taskStatusLabel(t.status)}</button></div>;
}
function TaskDialog({task,incidentId,evidence,onClose,onSave}:{task:ActionItem|'new'|null;incidentId:string;evidence:EvidenceEvent[];onClose:()=>void;onSave:Mutate}){return <Dialog open={!!task} onOpenChange={open=>!open&&onClose()}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{task==='new'?'Add an action':'Edit action'}</DialogTitle><DialogDescription>Keep the action specific, with one owner and a clear outcome.</DialogDescription></DialogHeader>{task&&<TaskForm key={typeof task==='string'?'new':task.id} incidentId={incidentId} task={task} evidence={evidence} onSave={async action=>{await onSave(action);onClose();toast.success('Action saved.');}}/>}</DialogContent></Dialog>;}
function TaskForm({task,incidentId,evidence,onSave}:{task:ActionItem|'new';incidentId:string;evidence:EvidenceEvent[];onSave:Mutate}){
 const [id]=useState(()=>crypto.randomUUID()),[draft,setDraft]=useState(task==='new'?{title:'',owner:'',priority:'medium',category:'mitigation',status:'open',dueAt:null as string|null,evidenceId:null as string|null,version:1}:taskPayload(task)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const set=(key:string,value:unknown)=>setDraft(d=>({...d,[key]:value}));
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(task==='new'){const {status,version,...data}=draft;await onSave({action:'create_task',id,data});}else await onSave({action:'update_task',id:task.id,data:draft});}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form onSubmit={submit}><fieldset className="ops-form" disabled={busy}><label>Action title<Input autoFocus required minLength={3} maxLength={240} value={draft.title} onChange={e=>set('title',e.target.value)} placeholder="e.g. Compare error rates after the rollback"/></label><label>Owner<Input maxLength={120} value={draft.owner} onChange={e=>set('owner',e.target.value)} placeholder="Name or team"/></label><div className="form-grid"><label>Priority<Picker label="Action priority" value={draft.priority} onChange={v=>set('priority',v)} options={options(['high','medium','low'])}/></label><label>Category<Picker label="Action category" value={draft.category} onChange={v=>set('category',v)} options={options(['mitigation','follow_up'])}/></label></div><div className="form-grid"><label>Due (your local time)<Input type="datetime-local" value={localTime(draft.dueAt)} onChange={e=>set('dueAt',utcTime(e.target.value))}/></label>{task!=='new'&&<label>Status<Picker label="Action status" value={draft.status} onChange={v=>set('status',v)} options={['open','in_progress','done'].map(value=>({value,label:taskStatusLabel(value)}))}/></label>}</div><label>Linked evidence<Picker label="Linked evidence" value={draft.evidenceId??'none'} onChange={v=>set('evidenceId',v==='none'?null:v)} options={[{value:'none',label:'No linked evidence'},...evidence.map(e=>({value:e.id,label:e.title})),...draft.evidenceId&&!evidence.some(e=>e.id===draft.evidenceId)?[{value:draft.evidenceId,label:'Existing linked event'}]:[]]}/></label>{task!=='new'&&draft.version!==task.version&&<div className="notice">A newer action is available.<details><summary>Compare saved action</summary><pre>{JSON.stringify(taskPayload(task),null,2)}</pre></details><button type="button" className="btn" onClick={()=>{setDraft(taskPayload(task));setError('')}}>Load saved action</button><button type="button" className="btn" onClick={()=>{setDraft({...draft,version:task.version});setError('')}}>Keep my draft over this version</button></div>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn primary" disabled={busy} type="submit"><Save size={15}/>{busy?'Saving…':'Save action'}</button></fieldset></form>;
}
function DecisionForm({mutate}:{mutate:Mutate}){
 const [body,setBody]=useState(''),[id,setId]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <form className="ops-form ops-panel-body" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await mutate({action:'decision',id,body});setBody('');setId(crypto.randomUUID());toast.success('Decision recorded.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Decision or observation<Textarea disabled={busy} rows={7} minLength={3} maxLength={5000} required value={body} onChange={e=>setBody(e.target.value)} placeholder="Decision: …\nEvidence considered: …\nExpected outcome: …\nWhat would change our mind: …"/></label><p className="ops-hint">Entries remain in the response history. Add a new entry to correct an earlier decision.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn primary" type="submit" disabled={busy}><Flag size={15}/>{busy?'Saving…':'Record decision'}</button></form>;
}
function PostmortemEditor({data,response,onSave,onActions}:{data:Workspace;response:ResponseData;onSave:(body:unknown)=>Promise<void>;onActions:()=>void}){
 const {draft,setDraft,dirty,setDirty}=useSavedDraft(`opscord:draft:${data.incident.id}:review`,response.postmortem);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!dirty)setDraft(response.postmortem)},[response.postmortem,dirty]);
 const set=(key:string,value:string)=>{setDraft(d=>({...d,[key]:value}));setDirty(true);};
 const fields=[['summary','What happened?','Summarize the incident without assigning blame.'],['impact','Customer impact','Describe affected users, services, duration, and known limits.'],['cause','Contributing factors','State the supporting evidence. “Cause not confirmed” is a valid finding.'],['response','Mitigation and recovery','Describe what was done and how recovery was verified.'],['lessons','What should change?','Capture what helped, what slowed the response, and how to prevent recurrence.']] as const;
 async function save(status:'draft'|'final'){setBusy(true);setError('');const {incidentId,updatedAt,...body}=draft;try{await onSave({...body,status});setDirty(false);toast.success(status==='final'?'Postmortem finalized.':'Postmortem draft saved.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function prefill(){setDraft(d=>({...d,summary:d.summary||response.coordination.summary,impact:d.impact||response.coordination.impact,response:d.response||data.incident.resolutionSummary||''}));setDirty(true);toast.info('Recorded facts added. Review and complete the remaining sections.');}
 const finalReady=data.incident.status==='resolved'&&fields.every(([key])=>draft[key].trim().length>=10);
 return <div className="postmortem-layout"><Panel title="Incident postmortem" sub="A blameless account of the evidence, response, and lessons" icon={FileCheck2} action={<Badge tone={response.postmortem.status==='final'?'teal':'amber'}>{response.postmortem.version?response.postmortem.status:'Not started'}</Badge>}><div className="ops-form ops-panel-body"><button className="btn prefill-btn" disabled={busy} onClick={prefill}><Copy size={15}/> Fill from saved incident facts</button>{fields.map(([key,label,placeholder])=><label key={key}>{label}<Textarea disabled={busy} value={draft[key]} onChange={e=>set(key,e.target.value)} rows={key==='summary'?4:3} maxLength={5000} placeholder={placeholder}/></label>)}{draft.version!==response.postmortem.version&&<div className="notice">A newer saved review is available. Your draft has been kept.<details><summary>Compare saved review</summary><pre>{JSON.stringify(response.postmortem,null,2)}</pre></details><button className="btn" disabled={busy} onClick={()=>{setDraft(response.postmortem);setDirty(false);setError('')}}>Load saved review</button><button className="btn" disabled={busy} onClick={()=>{setDraft({...draft,version:response.postmortem.version});setError('')}}>Keep my draft over this version</button></div>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><span className="ops-hint">{dirty?'Unsaved changes · kept on this device':response.postmortem.updatedAt?`Saved ${displayTime(response.postmortem.updatedAt)}`:'Draft not yet saved'}</span><button className="btn" disabled={busy} onClick={()=>void save('draft')}>Save draft</button><button className="btn primary" disabled={busy||!finalReady} onClick={()=>void save('final')}><CheckCheck size={15}/> Finalize review</button></div></div></Panel><div className="review-side"><Panel title="Ready for review"><div className="ops-panel-body review-checks"><p><Check size={16} className={data.incident.status==='resolved'?'teal-text':'muted'}/>Incident resolved</p>{fields.map(([key,label])=><p key={key}><Check size={16} className={draft[key].trim().length>=10?'teal-text':'muted'}/>{label}</p>)}<small>Complete each section with at least 10 characters. Finalizing saves this review; it does not publish it outside your workspace.</small></div></Panel><Panel title="Follow-up actions"><div className="ops-panel-body"><strong className="review-task-count">{response.tasks.filter(t=>t.category==='follow_up'&&t.status!=='done').length}</strong><p className="ops-hint">Open follow-ups. Give each improvement an owner and a due date.</p><button className="btn" onClick={onActions}>Manage actions <ArrowRight size={15}/></button></div></Panel><button className="btn" onClick={()=>download(`${data.incident.id}-evidence.json`,JSON.stringify({exportedAt:new Date().toISOString(),incident:data.incident,events:data.events,notes:data.notes,response},null,2),'application/json')}><Download size={15}/> Export incident data</button></div></div>;
}
export function exportResponse(data:Workspace,r:ResponseData){
 const c=r.coordination,p=r.postmortem;
 download(`${data.incident.id}-report.md`,[`# ${data.incident.title}`,`${data.incident.id} | ${data.incident.status} | ${data.incident.mode==='demo'?'Sample scenario':'Manual investigation'}`,`Started: ${data.incident.startedAt}\nResolved: ${data.incident.resolvedAt??'Not resolved'}`,`## Response brief\nCommander: ${c.owner||'Unassigned'}\nCommunications: ${c.communicationsLead||'Unassigned'}\nEnvironment: ${c.environment}\nNext update: ${c.nextUpdateAt??'Not scheduled'}\n\nImpact: ${c.impact||'Not recorded'}\n\nSituation: ${c.summary||'Not recorded'}`,`## Resolution\n${data.incident.resolutionSummary||'Not recorded'}`,`## Actions`,...r.tasks.map(t=>`- [${t.status==='done'?'x':' '}] ${t.title} | ${t.owner||'Unassigned'} | ${t.priority} | ${t.category} | Due: ${t.dueAt??'None'} | Evidence: ${t.evidenceId??'None'}`),`## Ranked hypotheses\nScores are heuristic evidence rankings, not causal probabilities.`,...data.candidates.map(c=>`### ${c.title} (${c.score}/100)\n${c.explanation}\nSupporting events: ${[c.seedId,...c.supportIds].join(', ')}\nNext step: ${c.nextStep}`),`## Evidence timeline`,...data.events.map(e=>`${e.occurredAt} | ${e.source} | ${e.service} | ${e.title}`),`## Response activity${r.activityTruncated?' (latest 200 entries)':''}`, ...[...r.activity].reverse().map(a=>`${a.createdAt} | ${a.kind} | ${a.message}`),`## Investigation notes`,...data.notes.map(n=>`${n.createdAt}: ${n.body}`),`## Postmortem (${p.status})`,...(['summary','impact','cause','response','lessons'] as const).map(k=>`### ${k}\n${p[k]||'Not recorded'}`)].join('\n\n'));
 toast.success('Complete incident report exported.');
}

export function OperationsWorkspace({view,data,onOpen,onCreate}:{view:string;data:Workspace;onOpen:(id:string,view?:string)=>void;onCreate:()=>void}){
 const [ops,setOps]=useState<OperationsData|null>(null),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const d=await api<OperationsData>('/api/operations');setOps(d);setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{void load()},[load,view,data]);
 if(!ops)return error?<Failure message={error} onRetry={()=>void load()}/>:<Loading/>;
 return <div className="ops-surface">{error&&<Failure message={error} onRetry={()=>void load()}/>}{(ops.incidentCount>data.incidents.length||ops.taskCount>ops.tasks.length)&&<div className="notice">Showing up to 100 recent incidents and 500 actions. Counts and charts below describe the loaded records.</div>}{view==='Incidents'?<IncidentQueue data={data} ops={ops} onOpen={onOpen} onCreate={onCreate}/>:view==='Actions'?<ActionBoard data={data} ops={ops} reload={load} onOpen={onOpen}/>:view==='Runbooks'?<RunbookLibrary books={ops.runbooks} data={data} reload={load} onOpen={onOpen}/>:<Insights data={data} ops={ops} onOpen={onOpen}/>}</div>;
}
function IncidentQueue({data,ops,onOpen,onCreate}:{data:Workspace;ops:OperationsData;onOpen:(id:string,view?:string)=>void;onCreate:()=>void}){
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[severity,setSeverity]=useState('all');
 const rows=data.incidents.filter(i=>{const c=ops.coordination.find(c=>c.incidentId===i.id);return(status==='all'||i.status===status)&&(severity==='all'||i.severity===severity)&&`${i.title} ${i.id} ${i.service} ${c?.owner??''}`.toLowerCase().includes(query.toLowerCase());});
 return <><div className="ops-toolbar"><label className="search-box"><Search size={17}/><Input aria-label="Search incidents" placeholder="Search incidents, services, or owners…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Picker label="Incident status filter" value={status} onChange={setStatus} options={[{value:'all',label:'All statuses'},...options(['active','investigating','resolved'])]}/><Picker label="Incident severity filter" value={severity} onChange={setSeverity} options={[{value:'all',label:'All severities'},...options(['critical','warning'])]}/><button className="btn primary" onClick={onCreate}><Plus size={15}/> New incident</button></div><div className="queue-count">{rows.length} of {data.incidents.length} loaded incidents</div>{rows.length?<div className="incident-queue">{rows.map(i=>{const c=ops.coordination.find(c=>c.incidentId===i.id),tasks=ops.tasks.filter(t=>t.incidentId===i.id&&t.status!=='done');return <button className="queue-card" key={i.id} onClick={()=>onOpen(i.id,'Response')}><div className="queue-main"><div className="queue-top"><Badge tone={i.status==='resolved'?'teal':'red'}>{i.status}</Badge><span>{i.id}</span>{i.mode==='demo'&&<Badge tone="amber">Sample</Badge>}</div><h3>{i.title}</h3><p>{c?.impact||'Customer impact has not been recorded.'}</p><div className="queue-meta"><span>{i.service}</span><span><Users size={14}/>{c?.owner||'Unassigned'}</span><span><Clock3 size={14}/>{displayTime(i.startedAt)}</span></div></div><div className="queue-side"><Badge tone={i.severity==='critical'?'red':'amber'}>{i.severity}</Badge><span>{tasks.length} open actions</span><ArrowRight size={19}/></div></button>})}</div>:<Empty title="No matching incidents" description="Try another search or filter, or declare a new incident."/>}</>;
}
function ActionBoard({data,ops,reload,onOpen}:{data:Workspace;ops:OperationsData;reload:()=>Promise<void>;onOpen:(id:string,view?:string)=>void}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('open'),[category,setCategory]=useState('all'),[edit,setEdit]=useState<ActionItem|null>(null);
 const rows=ops.tasks.filter(t=>(filter==='all'||filter==='open'&&t.status!=='done'||filter==='done'&&t.status==='done'||filter==='overdue'&&t.status!=='done'&&t.dueAt&&Date.parse(t.dueAt)<Date.now())&&(category==='all'||category===t.category)&&`${t.title} ${t.owner}`.toLowerCase().includes(query.toLowerCase()));
 const mutate=async(id:string,action:unknown)=>{try{await api(`/api/incidents/${id}/response`,'POST',action);}finally{await reload();}};
 return <><div className="ops-toolbar"><label className="search-box"><Search size={17}/><Input aria-label="Search actions" placeholder="Search actions or owners…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Picker label="Action filter" value={filter} onChange={setFilter} options={[{value:'open',label:'Open actions'},{value:'overdue',label:'Overdue'},{value:'done',label:'Completed'},{value:'all',label:'All actions'}]}/><Picker label="Action category filter" value={category} onChange={setCategory} options={[{value:'all',label:'All categories'},...options(['mitigation','follow_up'])]}/><button className="btn" onClick={()=>onOpen(data.incident.id,'Response')}><Plus size={15}/> Add in response plan</button></div><Panel title={`${rows.length} actions`} sub="Work across incidents, including sample scenarios"><div className="ops-panel-body">{rows.length?rows.map(t=><TaskRow key={t.id} task={t} incident={data.incidents.find(i=>i.id===t.incidentId)} onOpen={()=>onOpen(t.incidentId,'Response')} onEdit={()=>setEdit(t)} onToggle={()=>mutate(t.incidentId,{action:'update_task',id:t.id,data:taskPayload(t,t.status==='done'?'open':'done')})}/>):<Empty title="Nothing in this queue" description="Actions from incident response plans appear here. Adjust your filters to see completed work."/>}</div></Panel><TaskDialog task={edit?(ops.tasks.find(t=>t.id===edit.id)??edit):null} incidentId={edit?.incidentId??''} evidence={edit?.incidentId===data.incident.id?data.events:[]} onClose={()=>setEdit(null)} onSave={action=>mutate(edit!.incidentId,action)}/></>;
}
function RunbookLibrary({books,data,reload,onOpen}:{books:Runbook[];data:Workspace;reload:()=>Promise<void>;onOpen:(id:string,view?:string)=>void}){
 const [edit,setEdit]=useState<Runbook|'new'|null>(null),[busy,setBusy]=useState('');
 async function apply(book:Runbook){setBusy(book.id);try{await api(`/api/incidents/${data.incident.id}/response`,'POST',{action:'apply_runbook',id:book.id});toast.success(`${book.name} added to this incident. Existing steps were preserved.`);onOpen(data.incident.id,'Response');}catch(e){toast.error((e as Error).message)}finally{setBusy('')}}
 return <><div className="ops-toolbar"><p className="ops-hint">Checklists create saved actions for <strong>{data.incident.title}</strong>. Applying a checklist does not run commands.</p><button className="btn primary" onClick={()=>setEdit('new')}><Plus size={15}/> New runbook</button></div><div className="runbook-grid">{books.map(b=><Panel key={b.id} title={b.name} icon={BookOpen} action={<Badge>v{b.version}</Badge>}><div className="ops-panel-body"><p className="runbook-description">{b.description}</p><ol className="runbook-steps">{b.steps.map((s,i)=><li key={i}><span>{i+1}</span>{s}</li>)}</ol><div className="form-actions"><button className="btn" onClick={()=>setEdit(b)}>Edit runbook</button><button className="btn primary" disabled={!!busy} onClick={()=>void apply(b)}>{busy===b.id?'Applying…':'Apply checklist'}<ArrowRight size={15}/></button></div></div></Panel>)}</div><Dialog open={!!edit} onOpenChange={open=>!open&&setEdit(null)}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{edit==='new'?'Create a runbook':'Edit runbook'}</DialogTitle><DialogDescription>Changes affect future applications. Existing incident actions keep their original text.</DialogDescription></DialogHeader>{edit&&<RunbookForm book={edit} onSaved={async()=>{await reload();setEdit(null)}}/>}</DialogContent></Dialog></>;
}
function RunbookForm({book,onSaved}:{book:Runbook|'new';onSaved:()=>Promise<void>}){
 const [name,setName]=useState(book==='new'?'':book.name),[description,setDescription]=useState(book==='new'?'':book.description),[steps,setSteps]=useState(book==='new'?'':book.steps.join('\n')),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <form className="ops-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const data={name,description,steps:steps.split('\n').map(s=>s.trim()).filter(Boolean)};await api('/api/runbooks',book==='new'?'POST':'PATCH',book==='new'?data:{id:book.id,version:book.version,data});await onSaved();toast.success('Runbook saved.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Runbook name<Input required minLength={3} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>When to use it<Textarea maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Steps · one per line<Textarea required rows={9} value={steps} onChange={e=>setSteps(e.target.value)} maxLength={4820}/><small>Up to 20 steps, with 3–240 characters per step.</small></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn primary" disabled={busy}><Save size={15}/>{busy?'Saving…':'Save runbook'}</button></form>;
}
function Insights({data,ops,onOpen}:{data:Workspace;ops:OperationsData;onOpen:(id:string,view?:string)=>void}){
 const [window,setWindow]=useState('30');const incidents=data.incidents.filter(i=>window==='all'||Date.parse(i.startedAt)>=Date.now()-Number(window)*86400000),m=incidentMetrics(incidents,ops.tasks),live=incidents.filter(i=>i.mode==='live');
 const reviewed=live.filter(i=>ops.reviews.some(r=>r.incidentId===i.id&&r.status==='final')).length;
 const byService=serviceCatalog.map(s=>({...s,count:live.filter(i=>i.service===s.id).length})).filter(s=>s.count).sort((a,b)=>b.count-a.count);
 return <><div className="ops-toolbar"><p className="ops-hint">Manual incidents only. Sample scenarios are excluded. The period uses incident onset.</p><Picker label="Insights period" value={window} onChange={setWindow} options={[{value:'7',label:'Last 7 days'},{value:'30',label:'Last 30 days'},{value:'all',label:'All loaded history'}]}/></div><div className="insight-grid"><Metric label="Incidents" value={String(m.total)} sub={`${m.active} still active`}/><Metric label="Mean time to resolution" value={m.meanResolutionMs===null?'—':formatDuration(m.meanResolutionMs)} sub={`${m.resolved} resolved incidents · onset to latest resolution`}/><Metric label="Overdue actions" value={String(m.overdue)} sub="For incidents in this period"/><Metric label="Finalized postmortems" value={String(reviewed)} sub={`${m.resolved} resolved incidents in scope`}/></div><div className="response-columns"><Panel title="Incidents by service" sub="Recurrence in the selected period"><div className="ops-panel-body">{byService.length?byService.map(s=><div className="service-bar" key={s.id}><div><strong>{s.name}</strong><span>{s.count}</span></div><div><span style={{width:`${s.count/Math.max(...byService.map(s=>s.count))*100}%`}}/></div></div>):<Empty title="Your history starts with a real incident" description="Declare a manual incident to build your operational history. No sample data is included in these metrics."/>}</div></Panel><Panel title="Resolved incidents to learn from" sub="Complete the review and keep follow-up work moving"><div className="ops-panel-body">{live.filter(i=>i.status==='resolved').length?live.filter(i=>i.status==='resolved').map(i=><button className="review-incident" key={i.id} onClick={()=>onOpen(i.id,'Postmortem')}><div><strong>{i.title}</strong><small>{displayTime(i.resolvedAt)}</small></div><Badge tone={ops.reviews.some(r=>r.incidentId===i.id&&r.status==='final')?'teal':'amber'}>{ops.reviews.find(r=>r.incidentId===i.id)?.status??'Review needed'}</Badge><ArrowRight size={15}/></button>):<Empty title="No resolved incidents in this period" description="Resolved incidents will appear here with their postmortem status."/>}</div></Panel></div></>;
}
function Metric({label,value,sub}:{label:string;value:string;sub:string}){return <div className="insight-card"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>;}
